# Generated by Django 5.1.1 on 2024-09-24 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('docente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('fechanacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.carreras')),
            ],
        ),
        migrations.CreateModel(
            name='matriculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechamatricula', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.cursos')),
            ],
        ),
    ]
